# Generated by Django 2.1.15 on 2022-11-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('NoteId', models.AutoField(primary_key=True, serialize=False)),
                ('NoteDescription', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('Title', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('CreatedDate', models.DateTimeField(blank=True, default=None, max_length=500, null=True)),
                ('UpdatedDate', models.DateTimeField(blank=True, default=None, max_length=500, null=True)),
                ('CreatedBy', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('UpdatedBy', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('DeleteFlag', models.BooleanField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
    ]
